# Generated by Django 3.0.5 on 2020-04-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200429_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('food', 'food'), ('entertainment', 'entertainment'), ('health', 'health'), ('clothes', 'clothes'), ('others', 'others')], default='others', max_length=255),
        ),
    ]
