# Generated by Django 3.0.4 on 2020-04-30 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200429_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='billing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='app.Billing'),
        ),
    ]
