# Generated by Django 3.0.4 on 2020-05-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200430_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='app.Category'),
        ),
    ]
