# Generated by Django 3.0.4 on 2020-05-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200501_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='categories',
            field=models.ManyToManyField(blank=True, to='app.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('food', 'food'), ('entertainment', 'entertainment'), ('health', 'health'), ('clothes', 'clothes'), ('other', 'other')], default='other', max_length=255),
        ),
    ]
