# Generated by Django 3.0.4 on 2020-05-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200502_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='categories',
        ),
        migrations.AddField(
            model_name='bill',
            name='categories',
            field=models.CharField(blank=True, choices=[('food', 'food'), ('entertainment', 'entertainment'), ('health', 'health'), ('clothes', 'clothes'), ('other', 'other')], max_length=15),
        ),
    ]
