# Generated by Django 3.0.4 on 2020-05-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200502_2016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='bill',
            name='categories',
            field=models.CharField(choices=[('food', 'food'), ('entertainment', 'entertainment'), ('health', 'health'), ('clothes', 'clothes'), ('other', 'other')], max_length=15),
        ),
    ]
