# Generated by Django 3.0.4 on 2020-05-02 21:13

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        # ('taggit', '0003_taggeditem_add_unique_index'),
        ('app', '0008_auto_20200502_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='categories',
        ),
        migrations.AddField(
            model_name='bill',
            name='categories',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
