# Generated by Django 3.0.4 on 2020-05-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200502_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='categories',
        ),
        migrations.AddField(
            model_name='bill',
            name='categories',
            field=models.CharField(default='other', max_length=50),
        ),
    ]
