# Generated by Django 3.0.5 on 2020-05-03 16:30

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        # ('taggit', '0003_taggeditem_add_unique_index'),
        ('app', '0011_auto_20200503_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='categories',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
