# Generated by Django 3.0.5 on 2020-05-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200503_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['-name'],
            },
        ),

        migrations.RemoveField(
            model_name='bill',
            name='categories',
        ),
        migrations.AddField(
            model_name='bill',
            name='categories',
            field=models.ManyToManyField(to='app.Category'),
        )

    ]
