export const types = {
  AUTH_REQUEST: "AUTH_REQUEST",
  AUTH_SUCCESS: "AUTH_SUCCESS",
  AUTH_ERROR: "AUTH_ERROR",
  LOGOUT: "LOGOUT",
  START_LOADING: "START_LOADING",
  END_LOADING: "END_LOADING",
  SET_ERROR: "SET_ERROR",
  CLEAR_ERROR: "CLEAR_ERROR",
  SET_MESSAGE: "SET_MESSAGE",
  CLEAR_MESSAGE: "CLEAR_MESSAGE",
  SET_USER: "SET_USER",

  SET_BILLING: "SET_BILLING",
  CREATE_BILL: "CREATE_BILL",
  SET_BILLS: "SET_BILLS",
  SET_CATEGORIES: "SET_CATEGORIES"
};
